name: real_chat
description: A new Flutter project.
version: 1.0.0+1

publish_to: 'none'


environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  splashscreen: ^1.3.5
  file_picker: ^4.5.1
  flutter_chat_types: ^3.3.4
  image_picker: ^0.8.5
  flutter_chat_ui: ^1.5.8
  intl: ^0.17.0
  mime: ^1.0.1
  open_file: ^3.2.1
  uuid: ^3.0.6
  firebase_core: ^1.15.0
  cloud_firestore: ^3.1.13
  firebase_auth: ^3.3.16
  cloud_functions: ^3.2.13
  cupertino_list_tile: ^0.2.1
  flutter_chat_bubble: ^2.0.0
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1
  badges: ^2.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  mobx_codegen: ^2.0.6+2

flutter:
  uses-material-design: true
  
  assets:
    - assets/json/country.json
    - assets/logo.png
